spring:
  datasource:
    url: jdbc:mysql://realbricksdb-gamify.d.aivencloud.com:12183/defaultdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: avnadmin
    password: AVNS_xcoFUIS6alzL6A_DCuf
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: "admin_backend_v1"
  security:
    enabled: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 day in milliseconds
server:
  port: 8081
